Make all FFI _impl helpers safe rust (#212)
Several FFI entry points are split into a pair of function, where the
"inner" function does the actual work and returns a `DeltaResult` which
the "outer" function simply converts to `ExternResult`:
```rust
pub unsafe extern "C" fn foo(
      ... args ...,
    allocate_error: AllocateErrorFn,
) -> ExternResult<*mut Foo> {
    foo_impl(... args...).into_extern_result(allocate_error)
}
 
unsafe fn foo_impl(
      ... args ...,
    allocate_fn: AllocateErrorFn,
 ) -> DeltaResult<*mut Foo> {
   let foo = unsafe { ... args ... };
    ... do the actual work ...
}
```
This PR observes that the "outer" function can _also_ capture all the
unsafe code, so that the "inner" function becomes normal safe rust.